name: Inventory Management Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Go to the directory
        run: cd inventory-management
      - uses: actions/setup-node@v2
        with:
          node-version: "20"
      - run: npm install
      - run: npm run build
